spring.application.name=backend

spring.config.import=optional:dotenv:

spring.datasource.url=jdbc:mysql://localhost:3306/test_db
spring.datasource.username=hieuk
spring.datasource.password=123!@#123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true